#!/usr/bin/env python3
"""
Quick setup script for Supabase configuration.

This script helps you set up the .env file with your Supabase credentials.
"""

import os
from pathlib import Path


def create_env_file():
    """Create .env file with Supabase configuration."""
    print("🚀 Quick Supabase Setup")
    print("=" * 30)
    
    # Extract project ID from the URI
    project_id = "wbpupfkbjmncmjmhyfha"  # From your URI
    supabase_url = f"https://{project_id}.supabase.co"
    
    print(f"📋 Detected Supabase project: {supabase_url}")
    print("\nYou need to get your API keys from the Supabase dashboard:")
    print("1. Go to https://supabase.com/dashboard")
    print("2. Select your project")
    print("3. Go to Project Settings → API")
    print("4. Copy the 'anon public key' and 'service_role secret key'")
    
    # Get API keys
    print(f"\n🔑 Enter your Supabase API keys:")
    anon_key = input("Anon public key: ").strip()
    service_key = input("Service role key: ").strip()
    
    # Get other required keys
    print(f"\n🔑 Enter your other API keys:")
    openai_key = input("OpenAI API key: ").strip()
    apify_key = input("Apify API key: ").strip()
    
    # Create .env file
    env_content = f"""# Reddit Sentiment Analyzer Environment Configuration
# Generated by quick_setup.py

# Basic Settings
ENVIRONMENT=development
DEBUG=true
LOG_LEVEL=INFO

# API Configuration
API_HOST=0.0.0.0
API_PORT=8000

# External API Keys
OPENAI_API_KEY={openai_key}
APIFY_API_KEY={apify_key}

# Supabase Configuration
SUPABASE_URL={supabase_url}
SUPABASE_KEY={anon_key}
SUPABASE_SERVICE_ROLE_KEY={service_key}
SUPABASE_BRANDS_TABLE=brands
SUPABASE_RESULTS_TABLE=analysis_results

# Security
SECRET_KEY=dev-secret-key-change-in-production
JWT_SECRET_KEY=dev-jwt-secret-key
JWT_ALGORITHM=HS256
JWT_EXPIRATION_HOURS=24

# Feature Flags
ENABLE_CACHING=true
ENABLE_METRICS=true
ENABLE_TRACING=true
ENABLE_RATE_LIMITING=true
"""
    
    # Write .env file
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    
    # Show next steps
    print("\n🎯 Next Steps:")
    print("1. Create database tables in Supabase:")
    print("   - Go to your Supabase dashboard → SQL Editor")
    print("   - Run the SQL from supabase_setup_guide.md")
    print("\n2. Test your setup:")
    print("   python test_setup.py")
    print("\n3. Run analysis:")
    print("   python test_analysis.py")
    
    return True


def main():
    """Main setup function."""
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        return False
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        return False
    
    return True


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
