apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-analyzer
  namespace: reddit-analyzer
  labels:
    app: reddit-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit-analyzer
  template:
    metadata:
      labels:
        app: reddit-analyzer
    spec:
      containers:
      - name: reddit-analyzer
        image: reddit-sentiment-analyzer:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "false"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: reddit-analyzer-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: reddit-analyzer-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: reddit-analyzer-secrets
              key: openai-api-key
        - name: APIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: reddit-analyzer-secrets
              key: apify-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: logs
        emptyDir: {}
      - name: uploads
        emptyDir: {}
      restartPolicy: Always
